---
title: "1 - Introduction"
output: html_notebook
---

# Optimization makes everything endogenous

Experimental data is nice and clean but most of the data we have available to us as scientists is observational; It was generated by processes that didn't involve the researcher. The thing about ovservational data is that its usually generated with input from agents trying to do their best. This means that we should be distrustful of the correlations you find in the data because the values those variables take were chosen _endogenously_, ie. with input from the system itself. 

> The reason we think is because of what we learn from the potential outcomes model: a correlation, in order to be a measure of a causal effect, must be completely independent of the potential outcomes under consideration... Economic theory predicts choices will be endogenous, and thus naive correlations are misleading.

# Example: Identifying price elasticity of demand

_Economic models_ describe how the variables we are interested in relate and the hypothesis we would like to test. Then, the economic model becomes an _econometric model_ that we estimate from data by turning those variable relationships in to equations.

1. What is the functional form of the equation we want to fit?
2. How can we deal with important variables that cannot be directly observed or measured well?


## Ceteris paribus

If you want to examine the effect of a feature on the real world, you have to hold everything else constant. Honestly, most statistical techinques are just trying to do their best to approximate this.

Price elasticity of demand is the solution to the following equation. This can be interpreted as the percent change in quantity from a percent change in price.

$$
\epsilon = \frac{\partial log Q}{\partial log P}
$$

In order to draw a causal interpretation from this, one must hold everything else fixed - supply, prices of other goods, income, preferences, input costs, etc. We can control for such things in a regression:

$$
log Q_d = \alpha + \delta log P + \gamma X + u
$$

To estimate this regression equation, we need:

1. Numerous rows of data on price and quantity
2. The variation in price to be independent of $u$. Known as _exogeneity_.








