---
title: "Properties of Regression"
output: html_notebook
---

```{r setup}
library(tidyverse)

```

```{r}
set.seed(1)
obs <- 10000

df <- tibble(
  x = rnorm(obs),
  u = rnorm(obs),
  y = 5.5 * x + 12 * u)

fit <- lm(y ~ x, df)

df <- df %>% 
  mutate(yhat = predict(fit, df))

ggplot(df, aes(x, y)) +
  geom_vline(xintercept = 0, linetype = 2, size = .2) +
  geom_hline(yintercept = 0, linetype = 2, size = .2) +
  geom_point(size = .2, alpha = I(1/3)) + 
  geom_line(aes(x = x, y = yhat), size = .5) +
  annotate("text", y = 30, x = -3, 
           label = paste("y-intercept =", round(coef(fit)[1], 5)), 
           colour = "red", size = 3) +
    annotate("text", y = -30, x = 2.5, 
           label = paste("slope =", round(coef(fit)[2], 5)), 
           colour = "blue", size = 3) +
  theme(panel.background = element_rect(fill = "white", colour ="black")) +
  ggtitle("OLS Regression Line")
```

```{r}
df %>% 
  mutate(residuals = y - yhat) %>% 
  ggplot(aes(yhat, residuals)) +
    geom_hline(yintercept = 0) +
    geom_point(alpha = .8) +
    theme(panel.background = element_rect(fill = "white", colour ="black")) +
    xlab("Fitted values") + ylab("Residuals")
```

